"""Extract FFL random-Mii tables from the mii-creator TypeScript sources into a
Python module (m2a/_ffl_tables.py). The TS array literals are numeric-only, so
after stripping trailing commas they parse as JSON.
"""
import json, re, os

SRC = "/agent/workspace/mii2attr/mii-creator/src/external/ffl"
OUT = "/agent/workspace/mii2attr/m2a/_ffl_tables.py"


def grab_array(text, start_idx):
    """Bracket-match a [...] starting at the first '[' at/after start_idx."""
    i = text.index("[", start_idx)
    depth = 0
    for j in range(i, len(text)):
        if text[j] == "[":
            depth += 1
        elif text[j] == "]":
            depth -= 1
            if depth == 0:
                return text[i:j + 1]
    raise ValueError("unbalanced brackets")


def to_list(literal):
    # remove trailing commas before ] and parse as JSON
    cleaned = re.sub(r",(\s*\])", r"\1", literal)
    return json.loads(cleaned)


def extract_named(text, name):
    m = re.search(r"\b" + re.escape(name) + r"\b\s*(?::[^=]*)?=", text)
    if not m:
        raise ValueError(f"{name} not found")
    return to_list(grab_array(text, m.end()))


def main():
    random_parts = open(os.path.join(SRC, "RandomParts.ts")).read()
    db = open(os.path.join(SRC, "FFLiDatabaseRandom.ts")).read()
    charinfo = open(os.path.join(SRC, "FFLiCharInfo.ts")).read()

    names = [
        "RANDOM_PARTS_ARRAY_FACE_TYPE", "RANDOM_PARTS_ARRAY_HAIR_TYPE",
        "RANDOM_PARTS_ARRAY_EYE_TYPE", "RANDOM_PARTS_ARRAY_EYEBROW_TYPE",
        "RANDOM_PARTS_ARRAY_NOSE_TYPE", "RANDOM_PARTS_ARRAY_MOUTH_TYPE",
        "RANDOM_PARTS_ARRAY_FACE_LINE", "RANDOM_PARTS_ARRAY_FACE_MAKEUP",
        "RANDOM_PARTS_ARRAY_FACELINE_COLOR", "RANDOM_PARTS_ARRAY_HAIR_COLOR",
        "RANDOM_PARTS_ARRAY_EYE_COLOR",
    ]
    tables = {n: extract_named(random_parts, n) for n in names}
    tables["RANDOM_GLASS_TYPE"] = extract_named(db, "RANDOM_GLASS_TYPE")

    # two ROTATE arrays inside FFLiCharInfo.ts: first eye, then eyebrow.
    # anchor at '=' so the '[]' in the ': number[]' type annotation is skipped.
    ends = [m.end() for m in re.finditer(r"const\s+ROTATE[^=]*=", charinfo)]
    rot_eye = to_list(grab_array(charinfo, ends[0]))
    rot_eb = to_list(grab_array(charinfo, ends[1]))
    tables["ROTATE_EYE"] = rot_eye
    tables["ROTATE_EYEBROW"] = rot_eb

    with open(OUT, "w") as f:
        f.write('"""AUTO-GENERATED by tools/extract_ffl_tables.py. Do not edit.\n')
        f.write('Source: AnonymousUser98/mii-creator FFL random-Mii tables."""\n\n')
        for k, v in tables.items():
            f.write(f"{k} = {v!r}\n\n")

    # sanity
    print("ROTATE_EYE len", len(rot_eye), "ROTATE_EYEBROW len", len(rot_eb))
    print("FACE_TYPE dims", len(tables["RANDOM_PARTS_ARRAY_FACE_TYPE"]),
          len(tables["RANDOM_PARTS_ARRAY_FACE_TYPE"][0]),
          len(tables["RANDOM_PARTS_ARRAY_FACE_TYPE"][0][0]))
    print("EYE_COLOR", tables["RANDOM_PARTS_ARRAY_EYE_COLOR"])
    print("GLASS", tables["RANDOM_GLASS_TYPE"])
    print("wrote", OUT)


if __name__ == "__main__":
    main()
